### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by Zeusy123** [Dec64/pingrr#10]
THis is a modulae ive been looking for for AGES!!! so I hope we can get it working:)

Im on windowsserver 2008
python 27
all requirements are running 100% shown below:
D:\Appz\pingrr>pip install -r requirements.txt
Requirement already satisfied: requests~=2.18.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: BeautifulSoup4~=4.6.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: fuzzywuzzy~=0.15.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: python-Levenshtein~=0.12.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from python-Levenshtein~=0.12.0->-r requirements.txt (line 4))
-----------------------------------------

When i run first time, it askes me the questions to generate the config, but at the end it throws an error without creating the config file and i  see some errors below:

Do you want to use Trakt's anticipated list? (yes/no):
yes
[94mTrue[0m

Do you want to use Trakt's popular list? (yes/no):
yes
[94mTrue[0m

What is the minimum number of votes for a show to be grabbed?:

[94m[0m
------------------------------------------

At the end of answering all the config questions i see:

Traceback (most recent call last):
  File "pingrr.py", line 45, in <module>
    configuration.load()
  File "D:\Appz\pingrr\pingrr\config.py", line 169, in load
    self.create_config(self.settings['config'])
  File "D:\Appz\pingrr\pingrr\config.py", line 447, in create_config
    "runtime": int(filters_runtime),
ValueError: invalid literal for int() with base 10: ''
-------------------------

When i try running the script i get below error:

D:\Appz\pingrr>python pingrr.py
2018-03-04 16:21:39,349 pingrr.config INFO     Using default setting --loglevel=INFO
2018-03-04 16:21:39,351 pingrr.config INFO     Using default setting --blacklist=blacklist.json
2018-03-04 16:21:39,351 pingrr.config INFO     Using default setting --logfile=logs\pingrr.log
2018-03-04 16:21:39,351 pingrr.config INFO     Using default setting --config=config.json
Traceback (most recent call last):
  File "pingrr.py", line 45, in <module>
    configuration.load()
  File "D:\Appz\pingrr\pingrr\config.py", line 165, in load
    self.config = json.load(f)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 10 column 33 (char 191)

Any hlpe would be appreciated:)

**Comment by vertigo235** [comment]
Looks like you might be missing the runtime filter from your config

        "runtime": 0, ## Min runtime show/movie must have to be added

**Comment by vertigo235** [comment]
Actually sorry, it looks like you may have entered a blank value when it asked you to enter your min runtime, and then it failed at creating your config file.

**Comment by Dec64** [comment]
The config creation is a touch outdate unfortunately, haven't had time to re-do it. Best bet is to take the config on the readme and remove the comments and fill in your settings.

**Comment by Zeusy123** [comment]
Thanks for comming back to me, I have indeed just used the conffig on the readme and added my apis etc.. ive double checked and the runtime is in there, but above is still same errors:-/

**Comment by Dec64** [comment]
Could you please show us your config with the api's and sensitive information removed, preferably via pastebin or something.

**Comment by Zeusy123** [comment]
my confir.json file copiedfrom your frontpage and rmeove my private stuff:

{
    "allflicks": {
        "enabled": {
            "movies": true,
            "shows": false
        },
        "rating_match": 94
    },
    "filters": {
        "allow_canceled": true, ## allow shows that are cancelled to be added
        "allow_ended": true, ## allow shows that are finished to be added
        "country": ["gb","us","ca"], ## What countrys shows/movies are allowed to be from (whitelist)
        "genre": [], ## What genres shows/movies are NOT allowed to be from (blacklist)
        "language": "en", ## What language is allowed for shows/movies (whitelist)
        "network": "YouTube", ## What networks to NOT allow (blacklist)
        "rating": 3, ## Min rating show/movie must have to be added
        "runtime": 0, ## Min runtime show/movie must have to be added
        "votes": 1, ## Min votes show/movie must have to be added
        "year": {
            "movies": 0, ## Min year movie must be to be added
            "shows": 0 ## Min year show must be to be added
        }
    },
    "pingrr": {
        "limit": {
            "sonarr": 0, ## Amount of shows to be added per cycle
            "radarr": 0 ## Amount of movies to be added per cycle
        },
        "log_level": "info", ## Log level for pingrr
        "timer": 1.00, ## How long to wait, in hours, untill next scan
        "aired": 10 ## If show has less episodes then this aired, do not count towards limit
        "dry_run": False ## Set to true to not add any shows, just test filter results
    },
    "pushover": {
        "app_token": "",
        "enabled": true,
        "user_token": ""
    },
    "slack": {
        "channel": "",
        "enabled": false,
        "sender_icon": ":robot_face:",
        "sender_name": "Pingrr",
        "webhook_url": ""
    },
    "sonarr": {
        "api": "put my sonarr api key from general api key",
        "folder_path": "D:\Media\Current\Series Source", ## Default root folder path shows will be sent to
        "quality_profile": 1, ## Quality profile ID to assign to show in sonarr
        "monitored": true, ## Add show monitored or not
        "search_missing_episodes": true, ## Search for missing episodes on add or not
        "genre_paths": true, ## Use genre paths, change folder path for show depending on catagory
        "path_root": "/mnt/media/", ## Root of the path. Only need if using genre paths
        "paths": {  ## "Kids-TV": [children] == /mnt/media/Kids-TV for any show with genre "children". Add more as needed. Resolves in order. If show is Anime, will be sent to anime before Kids-TV in this example.
            "Anime": [
            "anime"
        ],
            "Kids-TV": [
            "children"
        ],
            "Travel-TV": [
            "documentary"
        ],
            "Reality-TV": [
            "reality",
                "game-show"
        ]
        }
    },
        "radarr": {
        "api": "",
        "folder_path": "D:\Media\Current\Movies Source",
        "host": "http://localhost:7878",
        "quality_profile": 1,
        "monitored": true,
        "genre_paths": true,
        "path_root": "D:\Media\Current",
        "paths": {
            "Anime": [
            "anime"
        ],
            "Kids-TV": [
            "children"
        ],
            "Travel-TV": [
            "documentary"
        ],
            "Reality-TV": [
            "reality",
                "game-show"
        ]
        }
    },
    "trakt": {
        "api": "My trakt id from trakt website is my username???", ## Client ID from trakt
        "imdb_info": false, ## Use imdb info for votes/genres/vote count if possible instead of trakt. WARNING, MUCH SLOWER THEN TRAKT.
        "limit": 2000, ## Max shows trakt will return. Use a higher number, e.g. 1000 to return a lot.
        "tv_list": {
            "anticipated": false,  ## Enable trakt tv anticipated
            "popular": false,	## Enable trakt tv popular
            "trending": false	## Enable trakt tv trending
        },
        "movie_list": {
            "anticipated": true, ## Enable trakt movie anticipated
            "popular": true, ## Enable trakt movie popular
            "trending": true ## Enable trakt movie trending
        }
    },
    "just_watch": {
        "enabled": {
            "movies": true, ## Enable justwatch for movies
            "shows": false ## Enable justwatch for shows
        },
        "country": "GB", ## What country to get justwatch info based on, e.g. GB or US
        "pages": "20" ## How many pages to get info from, 1 page = 1 day. Add more pages to add more content. Will be slower with more pages
    }
}
--------

hope u can see the problem??

**Comment by Dec64** [comment]
Can you please use pastebin or similar. That's a mess. Also i said remove the comments.

The comments are everything after, and including ##

**Comment by Dec64** [comment]
Here is my config, just edit that as a base instead...

https://pastebin.com/Hbtk6mM8

**Comment by Zeusy123** [comment]
Soz about pasting above in messy style:)
ive copied yours source confir, added my own details but still throwing same error:
I have upped what im putting into the required files and paths in this config,. can u see where im going wrong?  

https://pastebin.com/xEAAe9J1

**Comment by Dec64** [comment]
use jsonlint.com to validate your json file.

All your paths are wrong. I've edited it here

https://pastebin.com/jTTwYtef

You had "D:\Media\Current\Series Source"

instead of "D:/Media/Current/Series Source"

Use forward slash for paths not back slash.

**Comment by Zeusy123** [comment]
Thankyou for that:)

just have question on following:
    "trakt": {
        "api": "MY_TRACKT_USERNAME", <--this meant to be my trakt username? or am i to make a kep for this also???

**Comment by Dec64** [comment]
sorry? please check the readme on the front page. It's an API not a username

> Client ID from trakt

> Prerequisites
You will need a Trakt account and an API key (client ID), you can create a new API app in trakt here

**Comment by Zeusy123** [comment]
Thankyou once again great support..working now:)

**Comment by Dec64** [comment]
Cool, can you please close down the issue if every things fixed. Cheers
