### ISSUE TITLE
paths on windows 

### ISSUE THREAD

**Issue by Zeusy123** [Dec64/pingrr#11]
Soz to bother you again, but ran into another problem and im sure its my fault, but no sure why paths is an issue. In your log:

2018-03-05 13:48:18,661 root         INFO     Attempting to send to sonarr
2018-03-05 13:48:19,134 root         WARNING  Deception failed to be added to Sonarr! Adding to blacklist
2018-03-05 13:48:19,134 root         INFO     Attempting to send to sonarr
2018-03-05 13:48:19,414 root         WARNING  Rise failed to be added to Sonarr! Adding to blacklist
2018-03-05 13:48:19,414 root         INFO     Attempting to send to sonarr
2018-03-05 13:48:19,686 root         WARNING  American Woman failed to be added to Sonarr! Adding to blacklist
2018-03-05 13:48:19,687 root         INFO     Attempting to send to sonarr
2018-03-05 13:48:19,961 root         WARNING  The Launch failed to be added to Sonarr! Adding to blacklist
2018-03-05 13:48:19,963 root         INFO     Attempting to send to sonarr
2018-03-05 13:48:20,223 root         WARNING  Vida failed to be added to Sonarr! Adding to blacklist

Your scripts tried to add the 5 tvshow into sonarr however in sonarr log, I get:

Invalid request Validation failed: 
 -- Invalid Path

in my config the sonarr paths are:

 "sonarr": {
        "api": "3d84f93XXXXXXXX", 
        "folder_path": "D:/Media/Current/Series Source", 
        "genre_paths": false, 
        "host": "http://localhost:8989", 
        "monitored": true, 
        "path_root": "D:/Media/Current", 
        "paths": {
            "Anime": [
                "anime"
            ], 
            "Doc-TV": [
                "documentary"
            ], 
            "Kids-TV": [
                "children, family"
            ], 
            "Reality-TV": [
                "reality", 
                "game-show"
            ]
        }, 
-------------

Any ideas?

**Comment by Zeusy123** [comment]
checked the rootfolder field in sonarr db and it is "D:\Media\Current\Series Source"

**Comment by Dec64** [comment]
It seems windows uses backslash when everything else uses forward. So the path is indeed correct. It wont work currently in windows. I'd have to have a look at updating.

**Comment by Dec64** [comment]
Alternatively, there is a docker container you could run it in.

**Comment by Zeusy123** [comment]
:( any eta on when u can update so work on windows os??
i dont use docker

**Comment by Dec64** [comment]
No idea sorry, im very busy and this was a project kind of just for me that I uploaded on the off chance others my use it. I have a few things i want to look at but it could be a week, it could be months or never.

**Comment by Zeusy123** [comment]
AGH! 24hours wasted:(
Sad to hear:(

**Comment by Dec64** [comment]
use Docker, it's very easy.

**Comment by Zeusy123** [comment]
just installed  docker, see it in powershell but no idea how to make it work with your script:-/

**Comment by Dec64** [comment]
https://hub.docker.com/r/horjulf/pingrr/

Sorry i can't teach you how to use docker. Google how to create a container ect and use that

**Comment by Zeusy123** [comment]
no problem Dec64, really do appreciate the time you have given me.
msg me if u do decide to make your script work on windows, as im sure others would use it:)

**Comment by Zeusy123** [comment]
Did some research on this and heres what looks like the fix, hope it helps. this seems to rewrite the paths depending on the os for you so fix will make paths work correctly on linux and windows boxs.

https://askubuntu.com/questions/350458/passing-a-file-location-to-python

**Comment by Zeusy123** [comment]
if it does work, ill happily edit the file manually if you tell me where to edit:)

**Comment by Zeusy123** [comment]
another helpful page i hope:)

http://www.tutorialspoint.com/python/os_path_methods.htm

**Comment by Dec64** [comment]
Thanks for the information, but that's not really relevant. I did see something that perhaps you could try.

`D:\\Media\\Current\\Series Source
`
You could try double blackslash on all paths

**Comment by Zeusy123** [comment]
it works!!! :)

**Comment by Zeusy123** [comment]
now any idea how to make this run as a service in windows?:)  dont look for much assistance do I ?:)

**Comment by Dec64** [comment]
I already mentioned, I do not know anything about windows. Sorry.

Please close this issue if your issue is solved.

Cheers
