### ISSUE TITLE
Add To blacklist

### ISSUE THREAD

**Issue by Zeusy123** [Dec64/pingrr#13]
Be nice to add a show to a blacklist so its not put into sonarr or radarr:)

**Comment by Dec64** [comment]
> 
> ### Blacklist
> --
> 83 |  
> 84 | There is a blacklist.json file created on the first run. This file will
> 85 | have failed shows and any show you want to add to it outside of filters that
> … |  
> 86 | you never want to add. To add a show, either use the shows IMDB id or TVDB id.
> 
>

**Comment by Dec64** [comment]
**blacklist.json** should look like:
`{"blacklist": ["282424", "74703", "219431"]}`

**Comment by Zeusy123** [comment]
you sir, are a fecking star!! :)
finally got it to work with radarr also, your script seriously rocks!! 👍

**Comment by Zeusy123** [comment]
If i wish to add into blacklist a movie on radarr do i use the themoviedb number????

**Comment by Dec64** [comment]
It says in readme, use IMDB number

**Comment by Zeusy123** [comment]
its just that its added: 

LEGO DC Super Heroes: The Flash (themoviedb 493810- no imdb)- I already have this Lego DC Comics Super Heroes: The Flash in radarr.  (themoviedb 504997) I have tried delteing the one pingrr is importing but it continues to be imported in next run.  And as no imdb, i cant blacklist it.

Drake - God's Plan (themoviedb 513209) theres no imdb so cant blacklist it.
BTS: Burn The Stage (themoviedb 513145) theres no db. but when i search the name showing as tvseries??  how to blacklist this?

I hope you dont mind my reporting and asking for advice, I truly am only trying to help improve your fantastic script and certainly not complaining about it!:)

**Comment by Dec64** [comment]
I don't mind. The script is rather ghetto tho. I'm at work so can't check, have you tried adding the TMBid and see'ing if it works?

**Comment by Zeusy123** [comment]
nope shall try that now

**Comment by Zeusy123** [comment]
yep adding  themoviedb numbers into blacklist works in blacklisting:)

**Comment by Dec64** [comment]
Ok great
