### ISSUE TITLE
Demo/Dry Run Mode?

### ISSUE THREAD

**Issue by hongkongkiwi** [Dec64/pingrr#8]
Hi there,

Thanks for the great code! This is exactly what I was looking for.

I would like to suggest that you add a dry run/testing mode so we can play with different settings and see what kind of shows are picked up without actually adding them to Sonarr.

**Comment by Dec64** [comment]
Yeah that's something that's been considered. I will get around to it soon I hope.

**Comment by Dec64** [comment]
https://github.com/Dec64/pingrr/commit/e237542e4392a9c805451e0b9473c565bbc93b13

Done
